doc: add page for 'debug show generate-origins command'
terramate-io/terramate-docs pull request #31
Opened 2024-05-20 02:56 UTC by AnnuCode

2024-05-20 10:05 UTC, i4ki commented on cli/cmdline/debug/show/debug-show-generate-origins.md
> +terramate debug show generate-origins --chdir path/to/directory
```suggestion
terramate --chdir path/to/directory debug show generate-origins 
```
reasoning: `--chdir` is a global flag, so better to move it to beginning so it's not confused for being a "generate-origins" special flag.

Additionally, but this is minor, in every other example we use `-C <path>` (the short flag), so maybe makes sense to stick to one style.

2024-05-20 13:00 UTC, mariux requested changes

2024-05-20 13:00 UTC, mariux commented on cli/cmdline/debug/show/debug-show-generate-origins.md
> +terramate -C stacks/ --changed debug show generate-origins
```suggestion
terramate -C stacks debug show generate-origins --changed 
```

`--changed` will not stay a top level option.

2024-05-21 09:55 UTC, soerenmartius approved these changes

2024-05-21 10:32 UTC, merged